services:
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    env_file:
      - ./backend/.env
    volumes:
      - xreate-mysql-db:/var/lib/mysql
    ports:
      - "3306:3306" # Change the first number for different port
    networks:
      - xreate-network
  api:
    image: xreate_api
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "443:443" # Change the first number for different port
    expose:
      - "443" # 443 is default for https
    networks:
      - xreate-network
    depends_on:
      db:
        condition: service_healthy
      
volumes:
  xreate-mysql-db:
    driver: local

networks:
  xreate-network:
    driver: bridge